import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {
  // 1. Define your mapping here
  charMap: { [key: string]: string } = {
    'a' : 'w',
    'aa': 'wd',
    'A': 'we',
    'AA': 'wE',
    'i': 'b',
    'ii': 'B',
    'u': 'W',
    'U': 'W!',
    'Ri': 'R',
    'Rii': 'RD',
    'e': 't',
    'ee': 'ta',
    'o': 'T',
    'oo': 'ô',
    ".": "'",
    ',': '"',
    "'": 'z',
    '"': 'Z',
    'SRI': '›',
    'sri': '›',
    '?':'@', 
    'RA': '/',
    'RAA': '?',

    'c': 'la',
    'ca': 'l',
    'caa': 'ld',
    'cA': 'le',
    'cAA': 'lE',
    'co': 'fld',
    'coo': 'flda',
    'cu': 'l=',
    'cuu': 'l+',
    'ce': 'fl',
    'cee': 'flA',
    'ci': 'ls',
    'cii': 'lS',
    'cra': 'l%',
    'cro': 'fl%d',
    'croo': 'fl%da',
    'k': 'la',
    'ka': 'l',
    'kaa': 'ld',
    'kA': 'le',
    'kAA': 'lE',
    'ko': 'fld',
    'koo': 'flda',
    'ku': 'l=',
    'kuu': 'l+',
    'ke': 'fl',
    'kee': 'flA',
    'ki': 'ls',
    'kii': 'lS',
    'kra': 'l%',
    'kro': 'fl%d',
    'kroo': 'fl%da',
    'C': 'La',
    'Ca': 'L',
    'Caa': 'Ld',
    'CA': 'Le',
    'CAA': 'LE',
    'Co': 'fLd',
    'Coo': 'fLda',
    'Cu': 'L=',
    'Cuu': 'L+',
    'Ce': 'fL',
    'Cee': 'fLA',
    'Ci': 'Ls',
    'Cii': 'LS',  
    'Cra': 'L%',
    'Cro': 'fL%d',
    'Croo': 'fL%da',  
    'K': 'La',
    'Ka': 'L',
    'Kaa': 'Ld',
    'KA': 'Le',
    'KAA': 'LE',
    'Ko': 'fLd',
    'Koo': 'fLda',
    'Ku': 'L=',
    'Kuu': 'L+',
    'Ke': 'fL',
    'Kee': 'fLA',
    'Ki': 'Ls',
    'Kii': 'LS',  
    'Kra': 'L%',
    'Kro': 'fL%d',
    'Kroo': 'fL%da',  

    'g': '.a',
    'ga': '.',
    'gaa': '.d',
    'gA': '.e',
    'gAA': '.E',
    'go': 'f.d',
    'goo': 'f.da',
    'gu': '.=',
    'guu': '.+',
    'ge': 'f.',
    'gee': 'f.A',
    'gi': '.s',
    'gii': '.S',
    'gra': '.%',
    'gro': 'f.%d',
    'groo': 'f.%da',
    'G': '>a',
    'Ga': '>',
    'Gaa': '>d',
    'GA': '>e',
    'GAA': '>E',
    'Go': 'f>d',
    'Goo': 'f>da',
    'Gu': '>=',
    'Guu': '>+',
    'Ge': 'f>',
    'Gee': 'f>A',
    'Gi': '>s',
    'Gii': '>S',  
    'Gra': '>%',
    'Gro': 'f>%d',
    'Groo': 'f>%da',

    'ch': 'É',
    'cha': 'p',
    'chaa': 'pd',
    'chA': 'pe',
    'chAA': 'pE',
    'cho': 'fpd',
    'choo': 'fpda',
    'chu': 'pq',
    'chuu': 'pQ',
    'che': 'fp',
    'chee': 'fpA',
    'chi': 'Ñ',
    'chii': 'Ö',
    'chra': 'p%',
    'chro': 'fp%d',
    'chroo': 'fp%da',
    'CH': 'Pa',
    'CHa': 'P',
    'CHaa': 'Pd',
    'CHA': 'Pe',
    'CHAA': 'PE',
    'CHo': 'fPd',
    'CHoo': 'fPda',
    'CHu': 'Pq',
    'CHuu': 'PQ',
    'CHe': 'fP',
    'CHee': 'fPA',
    'CHi': 'Ps',
    'CHii': 'PS',  
    'CHra': 'P%',
    'CHro': 'fP%d',
    'CHroo': 'fP%da',

    't': 'Ü',
    'ta': 'g',
    'taa': 'gd',
    'tA': 'ge',
    'tAA': 'gE',
    'to': 'fgd',
    'too': 'fgda',
    'tu': 'gq',
    'tuu': 'gQ',
    'te': 'fg',
    'tee': 'fÜ',
    'ti': 'á',
    'tii': 'à',
    'tra': 'g%',
    'tro': 'fg%d',
    'troo': 'fg%da',
    'T': 'Ga',
    'Ta': 'G',
    'Taa': 'Gd',
    'TA': 'Ge',
    'TAA': 'GE',
    'To': 'fGd',
    'Too': 'fGda',
    'Tu': 'G=',
    'Tuu': 'G+',
    'Te': 'fG',
    'Tee': 'fGA',
    'Ti': 'Gs',
    'Tii': 'GS',  
    'Tra': 'G%',
    'Tro': 'fG%d',
    'Troo': 'fG%da',

    'd': 'â',
    'da': 'v',
    'daa': 'vd',
    'dA': 've',
    'dAA': 'vE',
    'do': 'fvd',
    'doo': 'fvda',
    'du': 'vq',
    'duu': 'vQ',
    'de': 'fv',
    'dee': 'fâ',
    'di': 'ä',
    'dii': 'ã',
    'dra': 'v%',
    'dro': 'fv%d',
    'droo': 'fv%da',
    'D': 'Ù',
    'Da': 'V',
    'Daa': 'Vd',
    'DA': 'Ve',
    'DAA': 'VE',
    'Do': 'fVd',
    'Doo': 'fVda',
    'Du': 'V=',
    'Duu': 'V+',
    'De': 'fV',
    'Dee': 'fVA',
    'Di': 'û',
    'Dii': 'ü',  
    'Dra': 'V%',
    'Dro': 'fV%d',
    'Droo': 'fV%da',

    'th': ';a',
    'tha': ';',
    'thaa': ';d',
    'thA': ';e',
    'thAA': ';E',
    'tho': 'f;d',
    'thoo': 'f;da',
    'thu': ';=',
    'thuu': ';+',
    'the': 'f;',
    'thee': 'f;A',
    'thi': ';s',
    'thii': ';S',
    'thra': ';%',
    'thro': 'f;%d',
    'throo': 'f;%da',
    'TH': ':a',
    'THa': ':',
    'THaa': ':d',
    'THA': ':e',
    'THAA': ':E',
    'THo': 'f:d',
    'THoo': 'f:da',
    'THu': ':=',
    'THuu': ':+',
    'THe': 'f:',
    'THee': 'f:A',
    'THi': ':s',
    'THii': ':S',  
    'THra': ':%',
    'THro': 'f:%d',
    'THroo': 'f:%da',

    'dh': 'oa',
    'dha': 'o',
    'dhaa': 'od',
    'dhA': 'oe',
    'dhAA': 'oE',
    'dho': 'fod',
    'dhoo': 'foda',
    'dhu': '¥',
    'dhuu': 'ª',
    'dhe': 'fo',
    'dhee': 'foA',
    'dhi': 'os',
    'dhii': 'oS',
    'dhra': 'ø',
    'dhro': 'fød',
    'dhroo': 'føda',
    'DH': 'Oa',
    'DHa': 'O',
    'DHaa': 'Od',
    'DHA': 'Oe',
    'DHAA': 'OE',
    'DHo': 'fOd',
    'DHoo': 'fOda',
    'DHu': 'O=',
    'DHuu': 'O+',
    'DHe': 'fO',
    'DHee': 'fOA',
    'DHi': 'Os',
    'DHii': 'OS',  
    'DHra': 'O%',
    'DHro': 'fO%d',
    'DHroo': 'fO%da',

    'n': 'ka',
    'na': 'k',
    'naa': 'kd',
    'nA': 'ke',
    'nAA': 'kE',
    'no': 'fkd',
    'noo': 'fkda',
    'nu': 'kq',
    'nuu': 'kQ',
    'ne': 'fk',
    'nee': 'fkA',
    'ni': 'ks',
    'nii': 'kS',
    'nra': 'k%',
    'nro': 'fk%d',
    'nroo': 'fk%da',
    'N': 'Ka',
    'Na': 'K',
    'Naa': 'Kd',
    'NA': 'Ke',
    'NAA': 'KE',
    'No': 'fKd',
    'Noo': 'fKda',
    'Nu': 'Kq',
    'Nuu': 'KQ',
    'Ne': 'fK',
    'Nee': 'fKA',
    'Ni': 'Ks',
    'Nii': 'KS',  
    'Nra': 'K%',
    'Nro': 'fK%d',
    'Nroo': 'fK%da',

    'p': 'ma',
    'pa': 'm',
    'paa': 'md',
    'pA': 'me',
    'pAA': 'mE',
    'po': 'fmd',
    'poo': 'fmda',
    'pu': 'mq',
    'puu': 'mQ',
    'pe': 'fm',
    'pee': 'fmA',
    'pi': 'ms',
    'pii': 'mS',
    'pra': 'm%',
    'pro': 'fm%d',
    'proo': 'fm%da',
    'pre': 'mA%',
    'P': 'Ma',
    'Pa': 'M',
    'Paa': 'Md',
    'PA': 'Me',
    'PAA': 'ME',
    'Po': 'fMd',
    'Poo': 'fMda',
    'Pu': 'Mq',
    'Puu': 'MQ',
    'Pe': 'fM',
    'Pee': 'fMA',
    'Pi': 'Ms',
    'Pii': 'MS',
    'Pra': 'M%',
    'Pro': 'fM%d',
    'Proo': 'fM%da',
    

    'b': 'í',
    'ba': 'n',
    'baa': 'nd',
    'bA': 'ne',
    'bAA': 'nE',
    'bo': 'fnd',
    'boo': 'fnda',
    'bu': 'nq',
    'buu': 'nQ',
    'be': 'fn',
    'bee': 'fí',
    'bi': 'ì',
    'bii': 'ï',
    'bra': 'n',
    'bro': 'fn%d',
    'broo': 'fn%da',
    'BH': 'Na',
    'BHa': 'N',
    'Bha': 'N', 
    'BHaa': 'Nd',
    'BHA': 'Ne',
    'BHAA': 'NE',
    'BHo': 'fNd',
    'BHoo': 'fNda',
    'BHu': 'N=',
    'BHuu': 'N+',
    'BHe': 'fN',
    'BHee': 'fNA',
    'BHi': 'Ns',
    'BHii': 'NS',  
    'BHra': 'N%',
    'BHro': 'fN%d',
    'BHroo': 'fN%da',
    'B': 'Na',
    'Ba': 'N', 
    'Baa': 'Nd',
    'BA': 'Ne',
    'BAA': 'NE',
    'Bo': 'fNd',
    'Boo': 'fNda',
    'Bu': 'N=',
    'Buu': 'N+',
    'Be': 'fN',
    'Bee': 'fNA',
    'Bi': 'Ns',
    'Bii': 'NS',  
    'Bra': 'N%',
    'Bro': 'fN%d',
    'Broo': 'fN%da',

    'm': 'ï',
    'ma': 'u',
    'maa': 'ud',
    'mA': 'ue',
    'mAA': 'uE',
    'mo': 'fud',
    'moo': 'fuda',
    'mu': 'uq',
    'muu': 'uQ',
    'me': 'fu',
    'mee': 'fï',
    'mi': 'ñ',
    'mii': 'ó',
    'mra': 'u%',
    'mro': 'fu%d',
    'mroo': 'fu%da', 

    'j': 'c',
    'ja': 'c',
    'jaa': 'cd',
    'jA': 'ce',
    'jAA': 'cE',
    'jo': 'fcd',
    'joo': 'fcda',
    'ju': 'cq',
    'juu': 'cQ',
    'je': 'fc',
    'jee': 'fcA',
    'ji': 'cs',
    'jii': 'cS',
    'jra': 'c%',
    'jro': 'fc%d',
    'jroo': 'fc%da',

    'y': 'h',
    'ya': 'h',
    'yaa': 'hd',
    'yA': 'he',
    'yAA': 'hE',
    'yo': 'fhd',
    'yoo': 'fhda',
    'yu': 'hq',
    'yuu': 'hQ',
    'ye': 'fh',
    'yee': 'fhA',
    'yi': 'hs',
    'yii': 'hS',
    'yra': 'h%',
    'yro': 'fh%d',
    'yroo': 'fh%da',
    
    'r': '¾',
    'ra': 'r',
    'raa': 'rd',
    'rA': 're',
    'rAA': 'rE',
    'ro': 'frd',
    'roo': 'frda',
    'ru': 're',
    'ruu': 'rE',
    're': 'fr',
    'ree': 'f¾',
    'ri': 'ß',
    'rii': 'Í',
    'rra': 'r%',
    'rro': 'fr%d',
    'rroo': 'fr%da',

    'l': ',a',
    'la': ',',
    'laa': ',d',
    'lA': ',e',
    'lAA': ',E',
    'lo': 'f,d',
    'loo': 'f,da',
    'lu': '¨',
    'luu': 'Æ',
    'le': 'f,',
    'lee': 'f,A',
    'li': ',s',
    'lii': ',S',
    'lra': ',%',
    'lro': 'f,%d',
    'lroo': 'f,%da',
    'L': '<a',
    'La': '<',
    'Laa': '<d',
    'LA': '<e',
    'LAA': '<E',
    'Lo': 'f<d',
    'Loo': 'f<da',
    'Lu': '<=',
    'Luu': '<+',
    'Le': 'f<',
    'Lee': 'f<A',
    'Li': '<s',
    'Lii': '<S',
    'Lra': '<%',
    'Lro': 'f<%d',
    'Lroo': 'f<%da',

    'v': 'õ',
    'va': 'j',
    'vaa': 'jd',
    'vA': 'je',
    'vAA': 'jE',
    'vo': 'fjd',
    'voo': 'fjda',
    'vu': 'jq',
    'vuu': 'jQ',
    've': 'fj',
    'vee': 'fõ',
    'vi': 'ú',
    'vii': 'ù',
    'vra': 'j%',
    'vro': 'fj%d',
    'vroo': 'fj%da',
    'w': 'õ',
    'wa': 'j',
    'waa': 'jd',
    'wA': 'je',
    'wAA': 'jE',
    'wo': 'fjd',
    'woo': 'fjda',
    'wu': 'jq',
    'wuu': 'jQ',
    'we': 'fj',
    'wee': 'fjA',
    'wi': 'ú',
    'wii': 'ù',
    'wra': 'j%',
    'wro': 'fj%d',
    'wroo': 'fj%da',

    's': 'ia',
    'sa': 'i',
    'saa': 'id',
    'sA': 'ie',
    'sAA': 'iE',
    'so': 'fid',
    'soo': 'fida',
    'su': 'iq',
    'suu': 'iQ',
    'se': 'fi',
    'see': 'fiA',
    'si': 'is',
    'sii': 'iS',
    'sra': 'i%',
    'sro': 'fi%d',
    'sroo': 'fi%da',
    'sh': 'Ia',
    'sha': 'I',
    'shaa': 'Id',
    'shA': 'Ie',
    'shAA': 'IE',
    'sho': 'fId',
    'shoo': 'fIda',
    'shu': 'Iq',
    'shuu': 'IQ',
    'she': 'fI',
    'shee': 'fIA',
    'shi': 'Is',
    'shii': 'IS',
    'shra': 'I%',
    'shro': 'fI%d',
    'shroo': 'fI%da',
    'S': 'Ya',
    'Sa': 'Y',
    'Saa': 'Yd',
    'SA': 'Ye',
    'SAA': 'YE',
    'So': 'fYd',
    'Soo': 'fYda',
    'Su': 'Yq',
    'Suu': 'YQ',
    'Se': 'fY',
    'See': 'fYA',
    'Si': 'Ys',
    'Sii': 'YS',
    'Sra': 'Y%',
    'Sro': 'fY%d',
    'Sroo': 'fY%da',

    'h': 'ya',
    'ha': 'y',
    'haa': 'yd',
    'hA': 'ye',
    'hAA': 'yE',
    'ho': 'fyd',
    'hoo': 'fyda',
    'hu': 'yq',
    'huu': 'yQ',
    'he': 'fy',
    'hee': 'fyA',
    'hi': 'ys',
    'hii': 'yS',
    'hra': 'y%',
    'hro': 'fy%d',
    'hroo': 'fy%da',

    'f': '*a',
    'fa': '*',
    'faa': '*d',
    'fA': '*e',
    'fAA': '*E',
    'fo': 'f*d',
    'foo': 'f*da',
    'fu': '*q',
    'fuu': '*Q',
    'fe': 'f*',
    'fee': 'f*A',
    'fi': '*s',
    'fii': '*S',
    'fra': '*%',
    'fro': 'f*%d',
    'froo': 'f*%da',
 

    
  };
  displayRules: { from: string; to: string }[] = [
    { from: 'x', to: 'x' },
    { from: 'RA', to: '/' },  
    { from: 'RAA', to: '?' }, 
  ];
  converterForm = new FormGroup({
    sourceInput: new FormControl(''),
    targetInput: new FormControl({ value: '', disabled: true })
  });

  ngOnInit() {
    // 2. Listen for changes in the source input
    this.converterForm.get('sourceInput')?.valueChanges.subscribe(val => {
      this.transformText(val || '');
    });
  }

  transformText(value: string) {
    let result = '';
    let i = 0;

    // Sort keys by length (longest first) so 'ka' is checked before 'k'
    const sortedKeys = Object.keys(this.charMap).sort((a, b) => b.length - a.length);

    while (i < value.length) {
      let matched = false;

      for (const key of sortedKeys) {
        if (value.startsWith(key, i)) {
          result += this.charMap[key];
          i += key.length; // Skip the length of the matched key
          matched = true;
          break;
        }
      }

      if (!matched) {
        result += value[i]; // No mapping found, keep original character
        i++;
      }
    }

    this.converterForm.patchValue({ targetInput: result }, { emitEvent: false });
  }
  // Inside your AppComponent class
copied = false;

copyToClipboard() {
  const textToCopy = this.converterForm.get('targetInput')?.value;
  
  if (textToCopy) {
    navigator.clipboard.writeText(textToCopy).then(() => {
      this.copied = true;
      
      // Reset the "Copied!" message after 2 seconds
      setTimeout(() => {
        this.copied = false;
      }, 2000);
    });
  }
}

}